{"name": "test_add_user_email_already_in_use", "status": "passed", "description": "TC002: Add User - 400 Bad request 'Email address \n    is already in use'", "attachments": [{"name": "log", "source": "e35f5fcc-8c34-4c5f-a62b-15eb17578f50-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e3f6fad0-a541-46ca-b9f8-61a0d8dd8882-attachment.txt", "type": "text/plain"}], "start": 1733918916817, "stop": 1733918917353, "uuid": "c0642b78-af8b-4616-a78f-4a3c663196b0", "historyId": "14599a2bb18ecfd40de8ecf52f94eaa3", "testCaseId": "14599a2bb18ecfd40de8ecf52f94eaa3", "fullName": "API.test_api#test_add_user_email_already_in_use", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "5cbf70c9ed4a"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}