{"name": "test_update_contact_unauthorized_put_method", "status": "passed", "description": "TC021: Unsuccessful update contact without auth token \n    and using PUT method", "attachments": [{"name": "log", "source": "3e882485-720d-45a6-9c0b-a01380b05501-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "407f744b-bcfb-4d91-9aca-a82244c8d56c-attachment.txt", "type": "text/plain"}], "start": 1733906256878, "stop": 1733906257005, "uuid": "d4a8439b-368a-4f55-9373-0589ed01b5ee", "historyId": "5ec8d11746d14b101f73c31211358a24", "testCaseId": "5ec8d11746d14b101f73c31211358a24", "fullName": "API.test_api#test_update_contact_unauthorized_put_method", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-0LB7JBM"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}